#!/bin/bash
me="$(basename "$0")"

# {{{ Getting the text from /dev/stdin
if [[ -d "${XDG_RUNTIME_DIR}" ]]; then
    CONFIGURED_RUNTIME_DIR="${XDG_RUNTIME_DIR}"
else
    CONFIGURED_RUNTIME_DIR="/tmp"
fi

STDIN=$(mktemp --tmpdir="${CONFIGURED_RUNTIME_DIR}" "${me}.XXXXXXXX") || {
    echo "Error: Failed to create temporary file." >&2
    exit 1
}

cat /dev/stdin > "${STDIN}"
# }}}

# {{{ Editor
CONFIGURED_EDITOR=${INFO_PRINT_EDITOR:-${EDITOR:-${VISUAL:-vi}}}
# }}}

# {{{ Saving the file or displaying it
CONFIGURED_FALLBACK_FILE="${CONFIGURED_RUNTIME_DIR}/info-print-output.txt"
if [[ -z "$TMUX" ]]; then
    if [[ -z ${XAUTHORITY} ]]; then
        COUNTER="${CONFIGURED_RUNTIME_DIR}/counter"
        if [[ ! -f "${COUNTER}" ]]; then
            COUNT=1
            echo "${COUNT}" > "${COUNTER}"
            chmod go-rwx,u=rw "${COUNTER}"
        else
            COUNT=$(cat "${COUNTER}")
            if ! [[ "${COUNT}" =~ ^[0-9]+$ ]]; then
                COUNT=1
            fi
            COUNT=$((COUNT + 1))
            echo "${COUNT}" > "${COUNTER}"
        fi
        cat "${STDIN}" > "${CONFIGURED_FALLBACK_FILE}"
    else
        CONFIGURED_X_TERMINAL_EMULATOR=$(command -v "${INFO_PRINT_X_TERMINAL_EMULATOR}" || command -v urxvt || command -v xterm)
        if [[ -z ${CONFIGURED_X_TERMINAL_EMULATOR} ]]; then
            echo "Error: No terminal emulator found. Set INFO_PRINT_X_TERMINAL_EMULATOR." >&2
            exit 2
        fi
        "${CONFIGURED_X_TERMINAL_EMULATOR}" -e "${CONFIGURED_EDITOR}" "${STDIN}"
    fi
else
    tmux new-window -n "info-print" "${CONFIGURED_EDITOR} ${STDIN}"
fi
# }}}

